const allNotifications = [{
  id: '123',
    unread: true,
    reason: 'author',
    updated_at: '2022-11-16T20:05:32Z',
    last_read_at: null,
    subject: {
    title: 'XPS-103742 - add text area character counter everywhere except alert description; additionally - change alert translations naming convention',
      url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/pulls/551',
      latest_comment_url: null,
      type: 'PullRequest'
  },
  repository: {
    id: 782347,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODIzNDc=',
      name: 'glass-webui',
      full_name: 'managed-security/glass-webui',
      'private': true,
      owner: {
      login: 'managed-security',
        id: 144510,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjE0NDUxMA==',
        avatar_url: 'https://avatars.github.***REMOVED***/u/144510?',
        gravatar_id: '',
        url: 'https://github.***REMOVED***/api/v3/users/managed-security',
        html_url: 'https://github.***REMOVED***/managed-security',
        followers_url: 'https://github.***REMOVED***/api/v3/users/managed-security/followers',
        following_url: 'https://github.***REMOVED***/api/v3/users/managed-security/following{/other_user}',
        gists_url: 'https://github.***REMOVED***/api/v3/users/managed-security/gists{/gist_id}',
        starred_url: 'https://github.***REMOVED***/api/v3/users/managed-security/starred{/owner}{/repo}',
        subscriptions_url: 'https://github.***REMOVED***/api/v3/users/managed-security/subscriptions',
        organizations_url: 'https://github.***REMOVED***/api/v3/users/managed-security/orgs',
        repos_url: 'https://github.***REMOVED***/api/v3/users/managed-security/repos',
        events_url: 'https://github.***REMOVED***/api/v3/users/managed-security/events{/privacy}',
        received_events_url: 'https://github.***REMOVED***/api/v3/users/managed-security/received_events',
        type: 'Organization',
        site_admin: false
    },
    html_url: 'https://github.***REMOVED***/managed-security/glass-webui',
      description: null,
      fork: false,
      url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui',
      forks_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/forks',
      keys_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/keys{/key_id}',
      collaborators_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/collaborators{/collaborator}',
      teams_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/teams',
      hooks_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/hooks',
      issue_events_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues/events{/number}',
      events_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/events',
      assignees_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/assignees{/user}',
      branches_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/branches{/branch}',
      tags_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/tags',
      blobs_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/blobs{/sha}',
      git_tags_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/tags{/sha}',
      git_refs_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/refs{/sha}',
      trees_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/trees{/sha}',
      statuses_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/statuses/{sha}',
      languages_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/languages',
      stargazers_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/stargazers',
      contributors_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/contributors',
      subscribers_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/subscribers',
      subscription_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/subscription',
      commits_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/commits{/sha}',
      git_commits_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/commits{/sha}',
      comments_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/comments{/number}',
      issue_comment_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues/comments{/number}',
      contents_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/contents/{+path}',
      compare_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/compare/{base}...{head}',
      merges_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/merges',
      archive_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/{archive_format}{/ref}',
      downloads_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/downloads',
      issues_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues{/number}',
      pulls_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/pulls{/number}',
      milestones_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/milestones{/number}',
      notifications_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/notifications{?since,all,participating}',
      labels_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/labels{/name}',
      releases_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/releases{/id}',
      deployments_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/deployments'
  },
  url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422',
    subscription_url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422/subscription'
}];

const allNewNotifications = [{
    id: '456',
    unread: true,
    reason: 'author',
    updated_at: '2022-11-16T21:06:32Z',
    last_read_at: null,
    subject: {
      title: 'XPS-103742 - add text area character counter everywhere except alert description; additionally - change alert translations naming convention',
      url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/pulls/551',
      latest_comment_url: null,
      type: 'PullRequest'
    },
    repository: {
      id: 782347,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODIzNDc=',
      name: 'glass-webui',
      full_name: 'managed-security/glass-webui',
      'private': true,
      owner: {
        login: 'managed-security',
        id: 144510,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjE0NDUxMA==',
        avatar_url: 'https://avatars.github.***REMOVED***/u/144510?',
        gravatar_id: '',
        url: 'https://github.***REMOVED***/api/v3/users/managed-security',
        html_url: 'https://github.***REMOVED***/managed-security',
        followers_url: 'https://github.***REMOVED***/api/v3/users/managed-security/followers',
        following_url: 'https://github.***REMOVED***/api/v3/users/managed-security/following{/other_user}',
        gists_url: 'https://github.***REMOVED***/api/v3/users/managed-security/gists{/gist_id}',
        starred_url: 'https://github.***REMOVED***/api/v3/users/managed-security/starred{/owner}{/repo}',
        subscriptions_url: 'https://github.***REMOVED***/api/v3/users/managed-security/subscriptions',
        organizations_url: 'https://github.***REMOVED***/api/v3/users/managed-security/orgs',
        repos_url: 'https://github.***REMOVED***/api/v3/users/managed-security/repos',
        events_url: 'https://github.***REMOVED***/api/v3/users/managed-security/events{/privacy}',
        received_events_url: 'https://github.***REMOVED***/api/v3/users/managed-security/received_events',
        type: 'Organization',
        site_admin: false
      },
      html_url: 'https://github.***REMOVED***/managed-security/glass-webui',
      description: null,
      fork: false,
      url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui',
      forks_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/forks',
      keys_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/keys{/key_id}',
      collaborators_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/collaborators{/collaborator}',
      teams_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/teams',
      hooks_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/hooks',
      issue_events_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues/events{/number}',
      events_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/events',
      assignees_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/assignees{/user}',
      branches_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/branches{/branch}',
      tags_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/tags',
      blobs_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/blobs{/sha}',
      git_tags_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/tags{/sha}',
      git_refs_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/refs{/sha}',
      trees_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/trees{/sha}',
      statuses_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/statuses/{sha}',
      languages_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/languages',
      stargazers_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/stargazers',
      contributors_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/contributors',
      subscribers_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/subscribers',
      subscription_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/subscription',
      commits_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/commits{/sha}',
      git_commits_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/commits{/sha}',
      comments_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/comments{/number}',
      issue_comment_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues/comments{/number}',
      contents_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/contents/{+path}',
      compare_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/compare/{base}...{head}',
      merges_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/merges',
      archive_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/{archive_format}{/ref}',
      downloads_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/downloads',
      issues_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues{/number}',
      pulls_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/pulls{/number}',
      milestones_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/milestones{/number}',
      notifications_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/notifications{?since,all,participating}',
      labels_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/labels{/name}',
      releases_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/releases{/id}',
      deployments_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/deployments'
    },
    url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422',
    subscription_url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422/subscription'
},
  {
    id: '789',
    unread: true,
    reason: 'author',
    updated_at: '2022-11-16T22:06:32Z',
    last_read_at: null,
    subject: {
      title: 'XPS-103742 - add text area character counter everywhere except alert description; additionally - change alert translations naming convention',
      url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/pulls/551',
      latest_comment_url: null,
      type: 'PullRequest'
    },
    repository: {
      id: 782347,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODIzNDc=',
      name: 'glass-webui',
      full_name: 'managed-security/glass-webui',
      'private': true,
      owner: {
        login: 'managed-security',
        id: 144510,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjE0NDUxMA==',
        avatar_url: 'https://avatars.github.***REMOVED***/u/144510?',
        gravatar_id: '',
        url: 'https://github.***REMOVED***/api/v3/users/managed-security',
        html_url: 'https://github.***REMOVED***/managed-security',
        followers_url: 'https://github.***REMOVED***/api/v3/users/managed-security/followers',
        following_url: 'https://github.***REMOVED***/api/v3/users/managed-security/following{/other_user}',
        gists_url: 'https://github.***REMOVED***/api/v3/users/managed-security/gists{/gist_id}',
        starred_url: 'https://github.***REMOVED***/api/v3/users/managed-security/starred{/owner}{/repo}',
        subscriptions_url: 'https://github.***REMOVED***/api/v3/users/managed-security/subscriptions',
        organizations_url: 'https://github.***REMOVED***/api/v3/users/managed-security/orgs',
        repos_url: 'https://github.***REMOVED***/api/v3/users/managed-security/repos',
        events_url: 'https://github.***REMOVED***/api/v3/users/managed-security/events{/privacy}',
        received_events_url: 'https://github.***REMOVED***/api/v3/users/managed-security/received_events',
        type: 'Organization',
        site_admin: false
      },
      html_url: 'https://github.***REMOVED***/managed-security/glass-webui',
      description: null,
      fork: false,
      url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui',
      forks_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/forks',
      keys_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/keys{/key_id}',
      collaborators_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/collaborators{/collaborator}',
      teams_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/teams',
      hooks_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/hooks',
      issue_events_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues/events{/number}',
      events_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/events',
      assignees_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/assignees{/user}',
      branches_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/branches{/branch}',
      tags_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/tags',
      blobs_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/blobs{/sha}',
      git_tags_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/tags{/sha}',
      git_refs_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/refs{/sha}',
      trees_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/trees{/sha}',
      statuses_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/statuses/{sha}',
      languages_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/languages',
      stargazers_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/stargazers',
      contributors_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/contributors',
      subscribers_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/subscribers',
      subscription_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/subscription',
      commits_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/commits{/sha}',
      git_commits_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/git/commits{/sha}',
      comments_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/comments{/number}',
      issue_comment_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues/comments{/number}',
      contents_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/contents/{+path}',
      compare_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/compare/{base}...{head}',
      merges_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/merges',
      archive_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/{archive_format}{/ref}',
      downloads_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/downloads',
      issues_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/issues{/number}',
      pulls_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/pulls{/number}',
      milestones_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/milestones{/number}',
      notifications_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/notifications{?since,all,participating}',
      labels_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/labels{/name}',
      releases_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/releases{/id}',
      deployments_url: 'https://github.***REMOVED***/api/v3/repos/managed-security/glass-webui/deployments'
    },
    url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422',
    subscription_url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422/subscription'
  }];

const subscriptions = [
  {
    id: '123',
    data: {
      subscribed: true,
      ignored: false,
      reason: 'author',
      created_at: '2022-09-01T08:39:52Z',
      url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422/subscription',
      thread_url: 'https://github.***REMOVED***/api/v3/notifications/threads/31161422'
    }
  }
];

const errorSubscriptions = [
  {
    id: '456',
    message: 'Not Found'
  }
];

module.exports = {
  allNotifications,
  allNewNotifications,
  subscriptions,
  errorSubscriptions
};