export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

export const GET_MORE_NOTIFICATIONS = 'GET_MORE_NOTIFICATIONS';
export const GET_MORE_NOTIFICATIONS_SUCCESS = 'GET_MORE_NOTIFICATIONS_SUCCESS';

export const SET_SINCE = 'SET_SINCE';

export const MOVE_NOTIFICATIONS = 'MOVE_NOTIFICATIONS';