export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS';
export const GET_SUBSCRIPTION_ERROR = 'GET_SUBSCRIPTION_ERROR';

export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const SET_SUBSCRIPTION_SUCCESS = 'SET_SUBSCRIPTION_SUCCESS';
export const SET_SUBSCRIPTION_ERROR = 'SET_SUBSCRIPTION_ERROR';
